version: '3.9'

services:
  web:
    build: .
    container_name: cashmatters-web
    command: gunicorn cashmatters.wsgi:application --bind 0.0.0.0:8000 --workers 3
    volumes:
      - ./cashmatters:/app/cashmatters   # <-- Mount your Django project
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DEBUG=0
      - ALLOWED_HOSTS=*
      - DATABASE_NAME=cashmatters_db
      - DATABASE_USER=cashmatters_user
      - DATABASE_PASSWORD=secure_password_123
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: cashmatters-db
    environment:
      POSTGRES_DB: cashmatters_db
      POSTGRES_USER: cashmatters_user
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: cashmatters-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
