version: '3'

services:
  cashmatters:
    container_name: cashmatters
    build:
      context: .
      dockerfile: config/cashmatters/Dockerfile
    environment:
      - CI_COMMIT_SHORT_SHA
    volumes:
      - ./:/cashmatters
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    expose:
      - "8000"   # Only exposed to other containers, not host
    networks:
      - cashmatters-net

  nginx:
    container_name: cashmatters-nginx
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    depends_on:
      - cashmatters
    networks:
      - cashmatters-net

volumes:
  static_volume:
  media_volume:

networks:
  cashmatters-net:
    driver: bridge
