# File structure version
# File structure version
version: '3'

services:

  cashmatters:
    environment:
      - CI_COMMIT_SHORT_SHA
    build:
      context: .
      dockerfile: config/cashmatters/Dockerfile
    hostname: cashmatters
    volumes:
      - ./:/cashmatters
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    expose:
      - "8000"      
  # Web server based on official nginx image
  # Connect external 8000 (which you can access from browser)
  # with internal port 8000(which will be linked to cashmatters port 8000 in configs)
  # Connect local nginx configuration with image configuration
  nginx:
    image: nginx
    hostname: nginx
    ports:
      - "80:80"
      - "443:443"
      - "8000:8000"
      - "5555:5555"
    volumes:
      - ./config/nginx/templates:/etc/nginx/templates
      - ./config/nginx:/etc/nginx/conf.d
      - ./config/nginx/.htpasswd:/etc/nginx/.htpasswd
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    env_file: .env
    depends_on:
      - cashmatters
#  redis:
#    image: redis:alpine

volumes:
  static_volume:
  media_volume: