services:
  web:
    build: .
    container_name: cashmatters-web
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    environment:
      - DJANGO_SETTINGS_MODULE=cashmatr.settings.base
      - DEBUG=0
      - ALLOWED_HOSTS=*
    depends_on:
      - db
    ports:
      - "8000:8000"

  db:
    image: postgres:15
    container_name: cashmatters-db
    environment:
      POSTGRES_DB: cashmatters_db
      POSTGRES_USER: cashmatters_user
      POSTGRES_PASSWORD: secure_password_123
    volumes:
      - ./pgdata:/var/lib/postgresql/data

  nginx:
    image: nginx:latest
    container_name: cashmatters-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - web
