nginx:
  image: nginx:latest
  container_name: cashmatters-nginx
  ports:
    - "80:80"
  volumes:
    - ./nginx/conf.d:/etc/nginx/conf.d   # mount host config to container
    - ./staticfiles:/app/staticfiles
    - ./media:/app/media
  depends_on:
    - web
