version: '3.8'

services:
  cashmatters:
    container_name: cashmatters
    build:
      context: .
      dockerfile: config/cashmatters/Dockerfile
    env_file:
      - .env
    volumes:
      - ./:/cashmatters
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    expose:
      - "8000"
    networks:
      - cashmatters-net

  nginx:
    container_name: cashmatters-nginx
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx:/etc/nginx/conf.d
      - static_volume:/cashmatters/static
      - media_volume:/cashmatters/media
    depends_on:
      - cashmatters
    networks:
      - cashmatters-net

volumes:
  static_volume:
  media_volume:

networks:
  cashmatters-net:
    driver: bridge
